### ISSUE TITLE
'I execute the SQL commands' fails if a query contains the character ';'

### ISSUE THREAD

**Issue by guewen** [camptocamp/oerpscenario#15]
The phrase 'I execute the SQL commands'  does a split of the character `;` to separate the queries in the text if it contains more than one: https://github.com/camptocamp/oerpscenario/blob/master/features/steps/tools.py#L30

The issue is that if a query contains a `;` inside a block of text, it will try to execute an incomplete query.

**Comment by nbessi** [comment]
Hmm didn't we fix this one
